# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MangoPlate Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MangoPlate Clone
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'Alamofire'
  pod 'naveridlogin-sdk-ios'
end
