# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoupangEats Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoupangEats Clone
  pod 'AFNetworking', '~> 2.6'
  pod 'Alamofire'
  pod 'AnyFormatKit'
end
